sudo: true
language: node
os: linux
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker build -t moleculerjs .
        - docker images
        - docker tag moleculerjs $DOCKER_USERNAME/moleculerjs
        - docker push $DOCKER_USERNAME/moleculerjs